### ISSUE TITLE
Cannot submit annotation(s) and (uninformative) error results

### ISSUE THREAD

**Issue by lreiser** [tair/toastdos-back#327]
As a user, after reviewing a submission the user cannot complete the submission. Clicking 'submit annotations' results in 'Submitting ' status displaying in the upper left corner for a long time and then finally an error alert appearing with no additional information.

When comparing the 'reviewed submission' forms there is clearly a difference in the information being displayed in the submission review.

Old form shows
1.Term:AT1G01220
2.qualifier : functions in (this is something added that depends on the ontology aspect)
3. Term name: kinase activity
4. Term ID: GO:0016301 (which links out to the GO site)
5.GO Evidence/GO Evidence code : inferred from direct assay , IDA
6.ECO method:enzyme inhibition assay evidence used in manual assertion (ECO:0007123), this links out to the ECO site.

The new submission review form displays the following elements
1.Gene name: AT2G23780
2.qualifier : functions in (this is something added that depends on the ontology aspect)
3.Term name: kinase activity
4.ECO method:enzyme inhibition assay evidence used in manual assertion  BUT NOT THE ID

I wonder if the problem has to do with the GO ID and GO evidence codes not being passed as these are absolute requirements for a submission.

Here is a sample annotation
![annotationtosubmit](https://user-images.githubusercontent.com/14040923/51951495-af7bf780-23e9-11e9-97be-493c433b8bda.png)

New version (after trying  unsuccessfully 
![new_submissionerror](https://user-images.githubusercontent.com/14040923/51951507-c4f12180-23e9-11e9-98dc-a44b7b9fb0df.png)
to submit)

Older version - submission review
![old_submissionreview](https://user-images.githubusercontent.com/14040923/51951515-cd495c80-23e9-11e9-8c73-4bc0adf0a1d6.png)

**Comment by qwertyflagstop** [comment]
I fixed the issue with submitting, it was a regression where I forgot to include the "isEvidenceWithOr" field. Going to clean up the review page now

**Comment by lreiser** [comment]
Able to submit 2 GO annotations for a single gene 
PMID: 30692244
encountered problems trying to annotate when more than one gene.(reporting in separate issue)

**Comment by lreiser** [comment]
Now cannot submit an annotation for a single gene at all. this may be tied to some of the issues that have not been addressed  such as  #355.
There are problems clearing the forms and then if I think I have cleared it then I still get some uniformative error message.
Upon submit
![screenshot_1581](https://user-images.githubusercontent.com/14040923/53470441-86657b80-3a16-11e9-89b0-63d30212ff26.png)

Going back to the data page to review the submission I see that the publication field is missing data (authors/title). Not sure how this relates to not 
![screenshot_1582](https://user-images.githubusercontent.com/14040923/53470533-bd3b9180-3a16-11e9-879c-a114abfa6491.png)

**Comment by qwertyflagstop** [comment]
Just pushed a fix for the uninformative error as well as form validation. I tested with various types of annotations.

**Comment by lreiser** [comment]
Per testing for #324
Unable to submit an anatomy term annotation

**Comment by lreiser** [comment]
Here is the 'error' on submit
![screenshot_1608](https://user-images.githubusercontent.com/14040923/53773481-81358000-3e9f-11e9-9a3b-5ccda7fa0ff0.png)

Oddly when I go back to 'edit' mode. There is something wrong with the publication display
Although I submitted a DOI the display now includes blank fields for authors/title.
![screenshot_1609](https://user-images.githubusercontent.com/14040923/53773541-bb068680-3e9f-11e9-9b8b-701f3878d52c.png)

very strange....

**Comment by lreiser** [comment]
Looking good. Fixing the warnings on the data entry page means that there should be no errors when trying to submit.
